FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# proyecto1

PROYECTO DE API CON BMW

## Questions Collection [/muchosbmw]

### muchosBMW [GET]

+ Response 200 (application/json)
    
      

        
        {
            "results":
            
            [ {   "year": 2016,
                "id": 34,
                "horsepower": 240,
                "make": "bmw",
                "model": "2-series",
                "price": 38650,
                "img_url": "https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/BMW-M240i-white-2016-coupe-%281%29.jpg"
            }
            ,
              {
                "year": 2016,
                "id": 35,
                "horsepower": 240,
                "make": "bmw",
                "model": "3-series",
                "price": 38350,
                "img_url": "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/15q2/657945/2016-bmw-3-series-photos-and-info-news-car-and-driver-photo-658769-s-original.jpg"
              },
              {
                "year": 2016,
                "id": 36,
                "horsepower": 300,
                "make": "bmw",
                "model": "3-series-gran-turismo",
                "price": 49200,
                "img_url": "https://www.km77.com/images/medium/0/0/2/7/bmw-serie3-gt-lateral-frontal.330027.jpg"
              },
              {
                "year": 2016,
                "id": 37,
                "horsepower": 300,
                "make": "bmw",
                "model": "4-series",
                "price": 56950,
                "img_url": "https://assets.whichcar.com.au/image/upload/s--eKJBaUGW--/ar_1.9047619047619047,c_fill,f_auto,q_auto:good/c_scale,w_1200/v1/archive/wheels/2016/06/22/67951/BMW-4-series-front-driving.jpg"
              },
              {
                "year": 2016,
                "id": 38,
                "horsepower": 300,
                "make": "bmw",
                "model": "4-series-gran-coupe",
                "price": 49950,
                "img_url": "https://images.drive.com.au/caradvice/image/private/c_fill,f_auto,g_auto,h_674,q_auto:eco,w_1200/3a50a4f853071271b046bdd00c1d1463"
              },
              {
                "year": 2016,
                "id": 39,
                "horsepower": 443,
                "make": "bmw",
                "model": "5-series",
                "price": 68600,
                "img_url": "https://www.diariomotor.com/imagenes/picscache/1440x655c/BMW_Serie_5_2013_700_2_1440x655c.jpg"
              },
              {
                "year": 2016,
                "id": 40,
                "horsepower": 300,
                "make": "bmw",
                "model": "5-series-gran-turismo",
                "price": 63200,
                "img_url": "https://media.ed.edmunds-media.com/bmw/5-series-gran-turismo/2016/oem/2016_bmw_5-series-gran-turismo_4dr-hatchback_535i_fq_oem_1_1600.jpg"
              },
              {
                "year": 2016,
                "id": 41,
                "horsepower": 315,
                "make": "bmw",
                "model": "6-series",
                "price": 77300,
                "img_url": "https://img.remediosdigitales.com/2612ff/bmw-serie-6-en-mexico--12-/1366_2000.jpg"
              },
              {
                "year": 2016,
                "id": 42,
                "horsepower": 315,
                "make": "bmw",
                "model": "6-series-gran-coupe",
                "price": 82500,
                "img_url": "http://cdn.wallapop.com/images/10420/9q/rm/__/c10420p589153847/i1865280408.jpg?pictureSize=W1024"
              },
              {
                "year": 2016,
                "id": 43,
                "horsepower": 445,
                "make": "bmw",
                "model": "7-series",
                "price": 94400,
                "img_url": "https://a.ccdn.es/cnet/contents/media/bmw/serie_7/1137093.jpg//937x624cut/"
              },
              {
                "year": 2016,
                "id": 44,
                "horsepower": 600,
                "make": "bmw",
                "model": "alpina-b6-gran-coupe",
                "price": 122200,
                "img_url": "https://media.ed.edmunds-media.com/bmw/alpina-b6-gran-coupe/2016/oem/2016_bmw_alpina-b6-gran-coupe_sedan_xdrive_fq_oem_1_1600.jpg"
              },
              {
                "year": 2015,
                "id": 45,
                "horsepower": 540,
                "make": "bmw",
                "model": "alpina-b7",
                "price": 132200,
                "img_url": "https://media.ed.edmunds-media.com/bmw/alpina-b7/2014/oem/2014_bmw_alpina-b7_sedan_swb_fq_oem_1_1600.jpg"
              },
              {
                "year": 2016,
                "id": 46,
                "horsepower": 335,
                "make": "bmw",
                "model": "activehybrid-5",
                "price": 62100,
                "img_url": "https://hips.hearstapps.com/es.h-cdn.co/cades/contenidos/5131/p90088765.jpg?resize=480:*"
              },
              {
                "year": 2015,
                "id": 47,
                "horsepower": 335,
                "make": "bmw",
                "model": "activehybrid-7",
                "price": 84300,
                "img_url": "https://cdcssl.ibsrv.net/autodata/images/?IMG=USC30BMC521A01305.JPG&width=680"
              },
              {
                "year": 2016,
                "id": 48,
                "horsepower": 365,
                "make": "bmw",
                "model": "m2",
                "price": 51700,
                "img_url": "https://cdn.topgear.es/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2016/11/bmw-m2-coupe-2016-xiv.jpg?itok=U76doVkn"
              },
              {
                "year": 2016,
                "id": 49,
                "horsepower": 425,
                "make": "bmw",
                "model": "m3",
                "price": 63500,
                "img_url": "https://w0.peakpx.com/wallpaper/868/120/HD-wallpaper-bmw-m3-drift-f80-2019-cars-supercars-tunned-m3-tuning-gray-m3-back-view-german-cars-gray-f80-bmw.jpg"
              },
              {
                "year": 2016,
                "id": 50,
                "horsepower": 425,
                "make": "bmw",
                "model": "m4",
                "price": 65700,
                "img_url": "https://pbs.twimg.com/media/BngO1yKIYAAyeLv.jpg"
              },
              {
                "year": 2016,
                "id": 51,
                "horsepower": 560,
                "make": "bmw",
                "model": "m5",
                "price": 94100,
                "img_url": "https://www.autopista.es/uploads/s1/79/64/48/2/e63-vs-m5-2.jpeg"
              },
              {
                "year": 2016,
                "id": 52,
                "horsepower": 552,
                "make": "bmw",
                "model": "m6",
                "price": 113400,
                "img_url": "https://i.pinimg.com/originals/8f/d7/b8/8fd7b8e5a776a7689aa772e974d3ff3e.jpg"
              },
              {
                "year": 2016,
                "id": 53,
                "horsepower": 552,
                "make": "bmw",
                "model": "m6-gran-coupe",
                "price": 117200,
                "img_url": "https://ag-spots-2016.o.auroraobjects.eu/2016/03/26/bmw-m6-f06-gran-coupe-2015-c614926032016054905_1.jpg"
              }
        ]}