FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# proyecto1

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/muchosbmw]

### muchosBMW [GET]

+ Response 200 (application/json)

        [
            {
                "year": 2016,
                "id": 34,
                "horsepower": 240,
                "make": "bmw",
                "model": "2-series",
                "price": 38650,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M8d2ce327068244565567a1db316398a6H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 35,
                "horsepower": 240,
                "make": "bmw",
                "model": "3-series",
                "price": 38350,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M23f6b0f90f24a3ec99fe227ef589c787H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 36,
                "horsepower": 300,
                "make": "bmw",
                "model": "3-series-gran-turismo",
                "price": 49200,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.Mc75fa0e340932e6cf464cd86e3634f67H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 37,
                "horsepower": 300,
                "make": "bmw",
                "model": "4-series",
                "price": 56950,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M9e5565480094a5717411c0ae75bee837H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 38,
                "horsepower": 300,
                "make": "bmw",
                "model": "4-series-gran-coupe",
                "price": 49950,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.M0d926544d83e5fbc63253d78424d492bo0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 39,
                "horsepower": 443,
                "make": "bmw",
                "model": "5-series",
                "price": 68600,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M9bc53ff98dd6355041b33ef32b33d9e9o0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 40,
                "horsepower": 300,
                "make": "bmw",
                "model": "5-series-gran-turismo",
                "price": 63200,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M7837b1c0e787a2bba280130d894225dfH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 41,
                "horsepower": 315,
                "make": "bmw",
                "model": "6-series",
                "price": 77300,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M2684e57d99815199e39737bc61a2eb64H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 42,
                "horsepower": 315,
                "make": "bmw",
                "model": "6-series-gran-coupe",
                "price": 82500,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.Mac27d3a378d6391fbae790116892e3f3H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 43,
                "horsepower": 445,
                "make": "bmw",
                "model": "7-series",
                "price": 94400,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M94fb4f09a477b76e2cd390330aeeb838H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 44,
                "horsepower": 600,
                "make": "bmw",
                "model": "alpina-b6-gran-coupe",
                "price": 122200,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.Mcb157e037f7fbcd69aa71771cb9744f4o0&pid=15.1"
              },
              {
                "year": 2015,
                "id": 45,
                "horsepower": 540,
                "make": "bmw",
                "model": "alpina-b7",
                "price": 132200,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.Med4626b4e1dde7937edddca49b960944H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 46,
                "horsepower": 335,
                "make": "bmw",
                "model": "activehybrid-5",
                "price": 62100,
                "img_url": "http://ts1.mm.bing.net/th?id=OIP.Mc2451243f52da622db6886fae2804340o0&pid=15.1"
              },
              {
                "year": 2015,
                "id": 47,
                "horsepower": 335,
                "make": "bmw",
                "model": "activehybrid-7",
                "price": 84300,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.M6bd068af8f088e25b8cd56276d430582o0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 48,
                "horsepower": 365,
                "make": "bmw",
                "model": "m2",
                "price": 51700,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.M6f0d4793d1b4c2624e947f935a477d08o0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 49,
                "horsepower": 425,
                "make": "bmw",
                "model": "m3",
                "price": 63500,
                "img_url": "http://ts1.mm.bing.net/th?id=OIP.Mc2544b1749e24db7e6cd00add0418290H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 50,
                "horsepower": 425,
                "make": "bmw",
                "model": "m4",
                "price": 65700,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.Mf11cbc701eace090d246e287181d46fbH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 51,
                "horsepower": 560,
                "make": "bmw",
                "model": "m5",
                "price": 94100,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M5e0d7d271dec276389600eeafacac4e0o0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 52,
                "horsepower": 552,
                "make": "bmw",
                "model": "m6",
                "price": 113400,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.Mdc6bb101eb9a788a07a58a5716abedcfo0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 53,
                "horsepower": 552,
                "make": "bmw",
                "model": "m6-gran-coupe",
                "price": 117200,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.Mde8ec5842856b4b7211eeb7ca41f9246H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 54,
                "horsepower": 228,
                "make": "bmw",
                "model": "x1",
                "price": 34800,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.M0f90d3554a09f2e7ea53210aeef868caH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 55,
                "horsepower": 300,
                "make": "bmw",
                "model": "x3",
                "price": 46800,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.Mf6315faccfb9cb4d52485fabec358403H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 56,
                "horsepower": 360,
                "make": "bmw",
                "model": "x4",
                "price": 57800,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M1b9ad0f0cf20b47bdd2d7e404fa7bd8cH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 57,
                "horsepower": 445,
                "make": "bmw",
                "model": "x5",
                "price": 71500,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.M0bf6e91ac412aa30b5e62fee045e3db5H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 58,
                "horsepower": 567,
                "make": "bmw",
                "model": "x5-m",
                "price": 98800,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.Mec012f08e524b6931ae2473537935d9bH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 59,
                "horsepower": 240,
                "make": "bmw",
                "model": "x5-edrive",
                "price": 62100,
                "img_url": "http://ts4.mm.bing.net/th?id=OIP.Mf833f47a924276fde133c495e2766e97o0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 60,
                "horsepower": 300,
                "make": "bmw",
                "model": "x6",
                "price": 60600,
                "img_url": "http://ts1.mm.bing.net/th?id=OIP.Me5cb5e3951c6ebbeda7ee4627d92d7feH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 61,
                "horsepower": 567,
                "make": "bmw",
                "model": "x6-m",
                "price": 102200,
                "img_url": "http://ts1.mm.bing.net/th?id=OIP.M0993ef7e55584816ac79cf850d775304H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 62,
                "horsepower": 335,
                "make": "bmw",
                "model": "z4",
                "price": 66350,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M866fb4ba5b8091690ad048e40ee35cffH0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 63,
                "horsepower": 170,
                "make": "bmw",
                "model": "i3",
                "price": 42400,
                "img_url": "http://ts3.mm.bing.net/th?id=OIP.M8383a16f24040cf25473ece30fc89f37H0&pid=15.1"
              },
              {
                "year": 2016,
                "id": 64,
                "horsepower": 357,
                "make": "bmw",
                "model": "i8",
                "price": 140700,
                "img_url": "http://ts2.mm.bing.net/th?id=OIP.M8cbb2251062f0f8b4a6b3f8a391af193o0&pid=15.1"
              }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }